# 构建部署

name: build-deploy
run-name: build-deploy
on:
    push:
        branches: [main]
permissions: write-all
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: setup-node-v20
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  cache: "npm"
            - name: build
              run: |
                  npm ci
                  npm install
                  npm run build
            - name: deploy
              run: |
                  git config --global user.email "pch1024@outlook.com"
                  git config --global user.name "pch1024"
                  cd dist
                  echo 'docs.peichenhu.cn' > CNAME
                  git init
                  git add -A
                  git commit -m 'deploy'
                  git push -f git@github.com:peichenhu/peichenhu.github.io.git master
                  cd -



