# 构建部署
# workflow_dispatch 允许您从“操作”选项卡手动运行此工作流

name: build-deploy
run-name: build-deploy
on:
    push:
        branches: [main]
    # 允许您从“操作”选项卡手动运行此工作流
    workflow_dispatch:
# 设置GITHUB_TOKEN的权限以允许部署到GITHUB页面
permissions:
    contents: read
    pages: write
    id-token: write
# 只允许一次并发部署，跳过在进行中的运行和最近排队的运行之间排队的运行。
# 但是，不要取消正在进行的运行，因为我们希望完成这些生产部署。
concurrency:
    group: pages
    cancel-in-progress: false
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: setup-node-v18
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: npm # or pnpm / yarn
            - name: build
              run: |
                  npm ci
                  npm install
                  npm run build
            - name: deploy
              run: |
                  git config --global user.email "pch1024@outlook.com"
                  git config --global user.name "pch1024"
                  cd dist
                  echo 'docs.peichenhu.cn' > CNAME
                  git init
                  git add -A
                  git commit -m 'deploy'
                  git push -f git@github.com:peichenhu/peichenhu.github.io.git master
                  cd -



