# ssh-keygen -t rsa -b 4096 -C "pch1024@outlook.com"

name: deploy
on:
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
            - run: pnpm install
            - name: ssh
              run: |
                  mkdir -p /home/runner/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
                  chmod 600 /home/runner/.ssh/id_rsa
                  ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            - run: pnpm deploy
