# ssh-keygen -t rsa -b 4096 -C "pch1024@outlook.com"

name: deploy
on:
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: true
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - uses: actions/setup-node@v3
            - run: npm ci # or pnpm install / yarn install / bun install
            - run: node -v
            - run: npm -v
            - run: npm run deploy
