# ssh-keygen -t rsa -b 4096 -C "pch1024@outlook.com"

name: deploy
on:
    push:
        branches: [main]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              # with:
              #     persist-credentials: true
              #     ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - uses: actions/setup-node@v3
            - run: npm ci # or pnpm install / yarn install / bun install
            - run: node -v
            - run: npm -v
            - name: Checkout repository
              run: |
                  mkdir -p /home/runner/.ssh/
                  echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
                  chmod 600 /home/runner/.ssh/id_rsa
                  ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            - run: npm run deploy
